"""Fix in_stock type

Revision ID: 2c269c81e925
Revises: d52fe4f985de
Create Date: 2025-04-18 22:51:29.884782

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2c269c81e925'
down_revision = 'd52fe4f985de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        # Add the USING clause to specify how to convert BOOLEAN to INTEGER
        batch_op.alter_column(
            'in_stock',
            existing_type=sa.BOOLEAN(),
            type_=sa.Integer(),
            nullable=False,
            postgresql_using='in_stock::integer'  # Convert BOOLEAN to INTEGER
        )
        batch_op.alter_column(
            'date_sold',
            existing_type=postgresql.TIMESTAMP(),
            nullable=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.alter_column(
            'date_sold',
            existing_type=postgresql.TIMESTAMP(),
            nullable=True
        )
        # Reverting the 'in_stock' column back to BOOLEAN
        batch_op.alter_column(
            'in_stock',
            existing_type=sa.Integer(),
            type_=sa.BOOLEAN(),
            nullable=True,
            postgresql_using='in_stock::boolean'  # Convert INTEGER back to BOOLEAN
        )

    # ### end Alembic commands ###
