"""Add in_stock column to Inventory model

Revision ID: 3256dfb4c7d9
Revises: d4177c2a7822
Create Date: 2025-04-18 03:57:02.471633

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3256dfb4c7d9'
down_revision = 'd4177c2a7822'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.add_column(sa.Column('in_stock', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.drop_column('in_stock')

    # ### end Alembic commands ###
