"""Add unique constraint on product ID and location

Revision ID: 3e5b8873b591
Revises: 79ac1745e53d
Create Date: 2025-04-22 00:29:46.223506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e5b8873b591'
down_revision = '79ac1745e53d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        # No need to drop 'product_identification_number_key' because it doesn't exist
        # batch_op.drop_constraint('product_identification_number_key', type_='unique')
        batch_op.create_unique_constraint('uq_product_identification_per_location', ['identification_number', 'location'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_constraint('uq_product_identification_per_location', type_='unique')
        # Reverting to the correct constraint for 'identification_number'
        batch_op.create_unique_constraint('product_identification_number_key', ['identification_number'])

    # ### end Alembic commands ###
