"""Add BakerInventory model clean

Revision ID: 73094448e05f
Revises: ddd2bc72f9d6
Create Date: 2025-09-11 11:55:36.942974

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '73094448e05f'
down_revision = 'ddd2bc72f9d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('baker_inventory', schema=None) as batch_op:
        batch_op.add_column(sa.Column('purchases', sa.JSON(), nullable=False, server_default='{}'))
        batch_op.add_column(sa.Column('breads', sa.JSON(), nullable=False, server_default='{}'))
        batch_op.alter_column('seller_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('ingredients')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('baker_inventory', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ingredients', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.alter_column('seller_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('breads')
        batch_op.drop_column('purchases')

    # ### end Alembic commands ###
