"""Remove seller_id from Product model

Revision ID: 79ac1745e53d
Revises: b6bcf63dc79e
Create Date: 2025-04-22 00:26:27.716368

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79ac1745e53d'
down_revision = 'b6bcf63dc79e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.alter_column('location',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.drop_constraint('product_seller_id_fkey', type_='foreignkey')
        batch_op.drop_column('seller_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('seller_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('product_seller_id_fkey', 'user', ['seller_id'], ['id'])
        batch_op.alter_column('location',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    # ### end Alembic commands ###
