"""Add is_read to Message

Revision ID: 7d06fc55232c
Revises: cbf2d05024e7
Create Date: 2025-05-02 10:35:47.186588

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d06fc55232c'
down_revision = 'cbf2d05024e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_read', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_column('is_read')

    # ### end Alembic commands ###
