"""Add inventory_id to Order

Revision ID: 8526fa0915cf
Revises: 5d20d35873e0
Create Date: 2025-04-25 11:29:11.281704

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8526fa0915cf'
down_revision = '5d20d35873e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('inventory_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'inventory', ['inventory_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('inventory_id')

    # ### end Alembic commands ###
