"""Add location to Product

Revision ID: 87159cc44ded
Revises: bdf7e38ab195
Create Date: 2025-04-20 01:17:50.700621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87159cc44ded'
down_revision = 'bdf7e38ab195'
branch_labels = None
depends_on = None


def upgrade():
    # Add location column as nullable first to avoid errors due to existing rows with null values
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.String(length=100), nullable=True))

    # You can update the existing rows to a default value if needed.
    # Example: Set default value for existing rows
    op.execute("UPDATE product SET location = 'Default Location' WHERE location IS NULL")

    # Alter the column to be non-nullable
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.alter_column('location', nullable=False)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('location')

    # ### end Alembic commands ###
