"""Add seller relationship to CreditSale

Revision ID: 99a0bbe9c942
Revises: bbb612e81e62
Create Date: 2025-09-18 21:17:26.646440

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '99a0bbe9c942'
down_revision = 'bbb612e81e62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('credit_sale')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credit_sale',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('customer_name', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('bread_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('amount_owing', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('date_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('seller_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('fully_paid', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['seller_id'], ['user.id'], name='credit_sale_seller_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='credit_sale_pkey')
    )
    # ### end Alembic commands ###
