"""Add status column to baker_inventory

Revision ID: a07059a1af9d
Revises: 73094448e05f
Create Date: 2025-09-11 15:22:43.609018

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a07059a1af9d'
down_revision = '73094448e05f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('baker_inventory', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('baker_inventory', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
