"""Add seller_id to Order

Revision ID: b17b32816802
Revises: 8526fa0915cf
Create Date: 2025-04-25 16:23:47.694261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b17b32816802'
down_revision = '8526fa0915cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('seller_id', sa.Integer(), nullable=True))

        batch_op.drop_constraint('order_inventory_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['seller_id'], ['id'])
        batch_op.drop_column('inventory_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('inventory_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('order_inventory_id_fkey', 'inventory', ['inventory_id'], ['id'])
        batch_op.drop_column('seller_id')

    # ### end Alembic commands ###
