"""Add fully_paid column to CreditSale

Revision ID: bbb612e81e62
Revises: 4ff878204c9e
Create Date: 2025-09-18 21:00:13.756695

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbb612e81e62'
down_revision = '4ff878204c9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('credit_sale', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fully_paid', sa.Boolean(), nullable=True))
        batch_op.alter_column('customer_name',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=150),
               existing_nullable=False)
        batch_op.alter_column('bread_type',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=100),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('credit_sale', schema=None) as batch_op:
        batch_op.alter_column('bread_type',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)
        batch_op.alter_column('customer_name',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)
        batch_op.drop_column('fully_paid')

    # ### end Alembic commands ###
