"""Add optional customer_phone to CreditSale

Revision ID: dd5946452e6c
Revises: b399c88f6ce0
Create Date: 2025-09-19 04:18:15.491944

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd5946452e6c'
down_revision = 'b399c88f6ce0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('credit_sale', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_phone', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('credit_sale', schema=None) as batch_op:
        batch_op.drop_column('customer_phone')

    # ### end Alembic commands ###
