"""Add location to Order

Revision ID: ddd2bc72f9d6
Revises: 9aa4d000bcc7
Create Date: 2025-09-03 17:07:12.313280

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ddd2bc72f9d6'
down_revision = '9aa4d000bcc7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('location')

    # ### end Alembic commands ###
